# Generated by Django 5.1.5 on 2025-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_order_payment_status_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In-Cart', 'In-Cart'), ('Pending', 'Pending'), ('In-Process', 'In-Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='In-Cart', max_length=100),
        ),
    ]
