# Generated by Django 5.1.5 on 2025-02-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='special_instruction',
            field=models.TextField(blank=True, default='Nothing', null=True),
        ),
    ]
